name: Manual Issue Transer Action Test
on:
  issues:
    types:
      - labeled

jobs:
  test-action:
    runs-on: ${{ matrix.os }}
    env:
      TERM: xterm
    strategy:
      matrix:
        os:
          - ubuntu-20.04
        router:
          - holla-tronic:crm-ops

    steps:
      - uses: actions/checkout@v2
      - name: Manual Action Test
        id: test_action
        uses: ./
        with:
          token: ${{ secrets.TRANSFER_ISSUE_TOKEN }}
          router: ${{ matrix.router }}
          apply_label: MANUAL ACTION TEST
          debug: true
